In [6]:
import sys
from pathlib import Path

# Add project root to Python path
PROJECT_ROOT = Path.cwd().parent
sys.path.insert(0, str(PROJECT_ROOT))

import sqlite3
import pandas as pd

from src.etl.loader import load_all_datasets

datasets = load_all_datasets()

print(f"Loaded {len(datasets)} datasets.")

RAW PATH: C:\Users\panka\OneDrive\Desktop\Nifty100_Project\data\raw
SUPPORTING PATH: C:\Users\panka\OneDrive\Desktop\Nifty100_Project\data\raw\supporting datasets
Loaded 12 datasets.

In [7]:
for name, df in datasets.items():
    print("=" * 80)
    print(name.upper())
    print("=" * 80)

    print("Shape:", df.shape)
    print("\nColumns:")
    print(df.columns.tolist())

    print("\nData Types:")
    print(df.dtypes)

    print("\n")

================================================================================
COMPANIES
================================================================================
Shape: (92, 12)

Columns:
['id', 'company_logo', 'company_name', 'chart_link', 'about_company', 'website', 'nse_profile', 'bse_profile', 'face_value', 'book_value', 'roce_percentage', 'roe_percentage']

Data Types:
id                  object
company_logo        object
company_name        object
chart_link          object
about_company       object
website             object
nse_profile         object
bse_profile         object
face_value         float64
book_value         float64
roce_percentage    float64
roe_percentage     float64
dtype: object


================================================================================
PROFITANDLOSS
================================================================================
Shape: (1276, 15)

Columns:
['id', 'company_id', 'year', 'sales', 'expenses', 'operating_profit', 'opm_percentage', 'other_income', 'interest', 'depreciation', 'profit_before_tax', 'tax_percentage', 'net_profit', 'eps', 'dividend_payout']

Data Types:
id                     int64
company_id            object
year                  object
sales                  int64
expenses               int64
operating_profit     float64
opm_percentage       float64
other_income           int64
interest               int64
depreciation           int64
profit_before_tax      int64
tax_percentage       float64
net_profit             int64
eps                  float64
dividend_payout      float64
dtype: object


================================================================================
BALANCESHEET
================================================================================
Shape: (1312, 13)

Columns:
['id', 'company_id', 'year', 'equity_capital', 'reserves', 'borrowings', 'other_liabilities', 'total_liabilities', 'fixed_assets', 'cwip', 'investments', 'other_asset', 'total_assets']

Data Types:
id                     int64
company_id            object
year                  object
equity_capital       float64
reserves               int64
borrowings             int64
other_liabilities      int64
total_liabilities      int64
fixed_assets           int64
cwip                   int64
investments            int64
other_asset            int64
total_assets           int64
dtype: object


================================================================================
CASHFLOW
================================================================================
Shape: (1187, 7)

Columns:
['id', 'company_id', 'year', 'operating_activity', 'investing_activity', 'financing_activity', 'net_cash_flow']

Data Types:
id                      int64
company_id             object
year                   object
operating_activity    float64
investing_activity    float64
financing_activity    float64
net_cash_flow         float64
dtype: object


================================================================================
ANALYSIS
================================================================================
Shape: (20, 6)

Columns:
['id', 'company_id', 'compounded_sales_growth', 'compounded_profit_growth', 'stock_price_cagr', 'roe']

Data Types:
id                           int64
company_id                  object
compounded_sales_growth     object
compounded_profit_growth    object
stock_price_cagr            object
roe                         object
dtype: object


================================================================================
DOCUMENTS
================================================================================
Shape: (1585, 4)

Columns:
['id', 'company_id', 'Year', 'Annual_Report']

Data Types:
id                int64
company_id       object
Year              int64
Annual_Report    object
dtype: object


================================================================================
PROSANDCONS
================================================================================
Shape: (16, 4)

Columns:
['id', 'company_id', 'pros', 'cons']

Data Types:
id             int64
company_id    object
pros          object
cons          object
dtype: object


================================================================================
FINANCIAL_RATIOS
================================================================================
Shape: (1184, 16)

Columns:
['id', 'company_id', 'year', 'net_profit_margin_pct', 'operating_profit_margin_pct', 'return_on_equity_pct', 'debt_to_equity', 'interest_coverage', 'asset_turnover', 'free_cash_flow_cr', 'capex_cr', 'earnings_per_share', 'book_value_per_share', 'dividend_payout_ratio_pct', 'total_debt_cr', 'cash_from_operations_cr']

Data Types:
id                               int64
company_id                      object
year                            object
net_profit_margin_pct          float64
operating_profit_margin_pct    float64
return_on_equity_pct           float64
debt_to_equity                 float64
interest_coverage              float64
asset_turnover                 float64
free_cash_flow_cr              float64
capex_cr                       float64
earnings_per_share             float64
book_value_per_share           float64
dividend_payout_ratio_pct      float64
total_debt_cr                    int64
cash_from_operations_cr        float64
dtype: object


================================================================================
MARKET_CAP
================================================================================
Shape: (552, 9)

Columns:
['id', 'company_id', 'year', 'market_cap_crore', 'enterprise_value_crore', 'pe_ratio', 'pb_ratio', 'ev_ebitda', 'dividend_yield_pct']

Data Types:
id                          int64
company_id                 object
year                        int64
market_cap_crore          float64
enterprise_value_crore    float64
pe_ratio                  float64
pb_ratio                  float64
ev_ebitda                 float64
dividend_yield_pct        float64
dtype: object


================================================================================
PEER_GROUPS
================================================================================
Shape: (56, 4)

Columns:
['id', 'peer_group_name', 'company_id', 'is_benchmark']

Data Types:
id                  int64
peer_group_name    object
company_id         object
is_benchmark         bool
dtype: object


================================================================================
SECTORS
================================================================================
Shape: (92, 6)

Columns:
['id', 'company_id', 'broad_sector', 'sub_sector', 'index_weight_pct', 'market_cap_category']

Data Types:
id                       int64
company_id              object
broad_sector            object
sub_sector              object
index_weight_pct       float64
market_cap_category     object
dtype: object


================================================================================
STOCK_PRICES
================================================================================
Shape: (5520, 9)

Columns:
['id', 'company_id', 'date', 'open_price', 'high_price', 'low_price', 'close_price', 'volume', 'adjusted_close']

Data Types:
id                  int64
company_id         object
date               object
open_price        float64
high_price        float64
low_price         float64
close_price       float64
volume              int64
adjusted_close    float64
dtype: object

In [8]:
for name, df in datasets.items():

    print("=" * 90)
    print(name.upper())
    print("=" * 90)

    print(f"Rows    : {len(df)}")
    print(f"Columns : {len(df.columns)}")

    print("\nNull Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows:", df.duplicated().sum())

    if "id" in df.columns:
        print("Duplicate IDs :", df["id"].duplicated().sum())

    print("\n")

==========================================================================================
COMPANIES
==========================================================================================
Rows    : 92
Columns : 12

Null Values
id                 0
company_logo       1
company_name       0
chart_link         0
about_company      0
website            1
nse_profile        1
bse_profile        1
face_value         1
book_value         1
roce_percentage    1
roe_percentage     2
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
PROFITANDLOSS
==========================================================================================
Rows    : 1276
Columns : 15

Null Values
id                     0
company_id             0
year                   0
sales                  0
expenses               0
operating_profit      13
opm_percentage        15
other_income           0
interest               0
depreciation           0
profit_before_tax      0
tax_percentage        95
net_profit             0
eps                    5
dividend_payout      103
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
BALANCESHEET
==========================================================================================
Rows    : 1312
Columns : 13

Null Values
id                   0
company_id           0
year                 0
equity_capital       0
reserves             0
borrowings           0
other_liabilities    0
total_liabilities    0
fixed_assets         0
cwip                 0
investments          0
other_asset          0
total_assets         0
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
CASHFLOW
==========================================================================================
Rows    : 1187
Columns : 7

Null Values
id                    0
company_id            0
year                  0
operating_activity    2
investing_activity    2
financing_activity    2
net_cash_flow         2
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
ANALYSIS
==========================================================================================
Rows    : 20
Columns : 6

Null Values
id                          0
company_id                  0
compounded_sales_growth     0
compounded_profit_growth    0
stock_price_cagr            0
roe                         0
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
DOCUMENTS
==========================================================================================
Rows    : 1585
Columns : 4

Null Values
id                0
company_id        0
Year              0
Annual_Report    52
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
PROSANDCONS
==========================================================================================
Rows    : 16
Columns : 4

Null Values
id            0
company_id    0
pros          5
cons          1
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
FINANCIAL_RATIOS
==========================================================================================
Rows    : 1184
Columns : 16

Null Values
id                              0
company_id                      0
year                            0
net_profit_margin_pct           1
operating_profit_margin_pct    61
return_on_equity_pct            0
debt_to_equity                  0
interest_coverage              93
asset_turnover                  1
free_cash_flow_cr               2
capex_cr                        2
earnings_per_share              4
book_value_per_share            0
dividend_payout_ratio_pct       4
total_debt_cr                   0
cash_from_operations_cr         2
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
MARKET_CAP
==========================================================================================
Rows    : 552
Columns : 9

Null Values
id                        0
company_id                0
year                      0
market_cap_crore          0
enterprise_value_crore    0
pe_ratio                  0
pb_ratio                  0
ev_ebitda                 0
dividend_yield_pct        0
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
PEER_GROUPS
==========================================================================================
Rows    : 56
Columns : 4

Null Values
id                 0
peer_group_name    0
company_id         0
is_benchmark       0
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
SECTORS
==========================================================================================
Rows    : 92
Columns : 6

Null Values
id                     0
company_id             0
broad_sector           0
sub_sector             0
index_weight_pct       0
market_cap_category    0
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0


==========================================================================================
STOCK_PRICES
==========================================================================================
Rows    : 5520
Columns : 9

Null Values
id                0
company_id        0
date              0
open_price        0
high_price        0
low_price         0
close_price       0
volume            0
adjusted_close    0
dtype: int64

Duplicate Rows: 0
Duplicate IDs : 0

In [9]:
db_path = PROJECT_ROOT / "data" / "db" / "nifty100.db"

conn = sqlite3.connect(db_path)
cursor = conn.cursor()

cursor.execute("PRAGMA foreign_keys = ON;")

print("Database created successfully.")

Database created successfully.

In [10]:
print(db_path)
print(db_path.exists())

c:\Users\panka\OneDrive\Desktop\Nifty100_Project\data\db\nifty100.db
True

In [11]:
schema_path = PROJECT_ROOT / "data" / "db" / "schema.sql"

with open(schema_path, "r", encoding="utf-8") as file:
    cursor.executescript(file.read())

conn.commit()

print("Schema executed successfully.")

Schema executed successfully.

In [12]:
tables = pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table'
ORDER BY name;
""", conn)

tables

                name
0           analysis
1       balancesheet
2           cashflow
3          companies
4          documents
5   financial_ratios
6         market_cap
7        peer_groups
8      profitandloss
9        prosandcons
10           sectors
11      stock_prices

In [20]:
cursor.execute("DELETE FROM profitandloss;")
cursor.execute("DELETE FROM companies;")
conn.commit()

In [21]:
companies = datasets["companies"]

companies.to_sql(
    "companies",
    conn,
    if_exists="append",
    index=False
)

print(f"Loaded {len(companies)} rows into companies.")

Loaded 92 rows into companies.

In [22]:
pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM companies;",
    conn
)

   total_rows
0          92

In [23]:
profitandloss = datasets["profitandloss"]

profitandloss.to_sql(
    "profitandloss",
    conn,
    if_exists="append",
    index=False
)

print(f"Loaded {len(profitandloss)} rows into profitandloss.")

Loaded 1177 rows into profitandloss.

In [16]:
companies_db = pd.read_sql(
    "SELECT id FROM companies",
    conn
)

print(companies_db.shape)
companies_db.head()

(92, 1)

           id
0         ABB
1  ADANIENSOL
2    ADANIENT
3  ADANIGREEN
4  ADANIPORTS

In [17]:
db_ids = set(companies_db["id"])
pl_ids = set(datasets["profitandloss"]["company_id"])

missing = sorted(pl_ids - db_ids)

print("Missing IDs:", missing)
print("Count:", len(missing))

Missing IDs: ['ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'VBL', 'VEDL', 'WIPRO', 'ZOMATO', 'ZYDUSLIFE']
Count: 8

In [18]:
print(repr(companies_db.iloc[0]["id"]))
print(repr(datasets["profitandloss"].iloc[0]["company_id"]))

'ABB'
'ABB'

In [19]:
valid_ids = set(datasets["companies"]["id"])

print("Removing orphan records...\n")

for table, df in datasets.items():

    if "company_id" in df.columns:

        before = len(df)

        datasets[table] = df[df["company_id"].isin(valid_ids)].copy()

        after = len(datasets[table])

        print(f"{table:<20} Removed: {before-after:>3} rows | Remaining: {after}")

Removing orphan records...

profitandloss        Removed:  99 rows | Remaining: 1177
balancesheet         Removed:  85 rows | Remaining: 1227
cashflow             Removed:  96 rows | Remaining: 1091
analysis             Removed:   4 rows | Remaining: 16
documents            Removed: 128 rows | Remaining: 1457
prosandcons          Removed:   2 rows | Remaining: 14
financial_ratios     Removed:  24 rows | Remaining: 1160
market_cap           Removed:   0 rows | Remaining: 552
peer_groups          Removed:   0 rows | Remaining: 56
sectors              Removed:   0 rows | Remaining: 92
stock_prices         Removed:   0 rows | Remaining: 5520

In [28]:
tables = [
    "companies",
    "profitandloss",
    "balancesheet",
    "cashflow",
    "analysis",
    "documents",
    "prosandcons",
    "financial_ratios",
    "market_cap",
    "peer_groups",
    "sectors",
    "stock_prices"
]

for table in tables:
    count = pd.read_sql(
        f"SELECT COUNT(*) AS rows FROM {table}",
        conn
    ).iloc[0, 0]

    print(f"{table:<20} {count}")

companies            92
profitandloss        1177
balancesheet         1227
cashflow             1091
analysis             16
documents            1457
prosandcons          14
financial_ratios     1160
market_cap           552
peer_groups          56
sectors              92
stock_prices         5520

In [30]:
load_audit = []

for table in [
    "companies",
    "profitandloss",
    "balancesheet",
    "cashflow",
    "analysis",
    "documents",
    "prosandcons",
    "financial_ratios",
    "market_cap",
    "peer_groups",
    "sectors",
    "stock_prices"
]:
    rows = pd.read_sql(
        f"SELECT COUNT(*) AS rows FROM {table}",
        conn
    ).iloc[0, 0]

    load_audit.append({
        "table": table,
        "rows_loaded": rows,
        "status": "Success"
    })

audit = pd.DataFrame(load_audit)
audit

               table  rows_loaded   status
0          companies           92  Success
1      profitandloss         1177  Success
2       balancesheet         1227  Success
3           cashflow         1091  Success
4           analysis           16  Success
5          documents         1457  Success
6        prosandcons           14  Success
7   financial_ratios         1160  Success
8         market_cap          552  Success
9        peer_groups           56  Success
10           sectors           92  Success
11      stock_prices         5520  Success

In [31]:
audit.to_csv(
    PROJECT_ROOT / "output" / "load_audit.csv",
    index=False
)

print("Load audit saved successfully.")

Load audit saved successfully.